theme = "nord_light"

[editor]
line-number = "relative"
cursorline = true
true-color = true
color-modes = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
